const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEYS={url:'kip_gas_web_app_url',token:'kip_gas_session_token'};
const state={token:sessionStorage.getItem(KEYS.token)||'',materials:[],date:'',health:null,assetCache:new Map()};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function status(el,msg,kind='info'){el.textContent=msg;el.className='status '+kind;}
function clearStatus(el){el.textContent='';el.className='status hidden';}
function btnBusy(btn,label){const old=btn.innerHTML;btn.disabled=true;btn.innerHTML='<span class="loader"></span>'+label;return()=>{btn.innerHTML=old;btn.disabled=false;};}
function gasUrl(){return(localStorage.getItem(KEYS.url)||'').trim();}
function validUrl(u){try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='script.google.com'&&/\/macros\/s\/.+\/exec$/.test(x.pathname);}catch{return false;}}
async function gas(action,payload={},auth=true){if(!validUrl(gasUrl()))throw new Error('Apps Script /exec URL is not configured.');const r=await fetch(gasUrl(),{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...(auth?{token:state.token}:{}),...payload})});const t=await r.text();let d;try{d=JSON.parse(t);}catch{throw new Error('Unreadable Apps Script response. Use the deployed /exec URL.');}if(!d.ok){if(['AUTH_REQUIRED','AUTH_EXPIRED'].includes(d.code)){state.token='';sessionStorage.removeItem(KEYS.token);showLogin();}const e=new Error(d.error||'Request failed');e.code=d.code;throw e;}return d;}
function shortErr(e){const s=e?.message||String(e);return s.length>240?s.slice(0,237)+'…':s;}
function fmtDate(s){if(!s)return'—';const[y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(y,m-1,d));}
function fmtTime(iso){if(!iso)return'—';const d=new Date(iso);if(isNaN(d))return iso;return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Jakarta'}).format(d)+' WIB';}
function expiryText(iso){if(!iso)return'—';const ms=new Date(iso).getTime()-Date.now();if(ms<=0)return'Expired';const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return`${h}h ${m}m left`;}
function showLogin(){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#gasUrlInput').value=gasUrl();}
function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');refreshHealth();}
$('#saveGasUrlBtn').onclick=()=>{const u=$('#gasUrlInput').value.trim();if(!validUrl(u))return status($('#loginStatus'),'Use the deployed Apps Script URL ending in /exec.','error');localStorage.setItem(KEYS.url,u);status($('#loginStatus'),'Connection saved in this browser.','ok');};
$('#loginForm').onsubmit=async e=>{e.preventDefault();clearStatus($('#loginStatus'));const done=btnBusy($('#loginBtn'),'Signing in…');try{const d=await gas('login',{email:$('#loginEmail').value.trim(),password:$('#loginPassword').value},false);state.token=d.token;sessionStorage.setItem(KEYS.token,d.token);$('#loginPassword').value='';showApp();}catch(e){status($('#loginStatus'),shortErr(e),'error');}finally{done();}};
$('#logoutBtn').onclick=()=>{state.token='';sessionStorage.removeItem(KEYS.token);showLogin();};
async function checkSession(){if(!state.token||!validUrl(gasUrl()))return showLogin();try{await gas('auth');showApp();}catch{showLogin();}}

async function refreshHealth(){try{state.health=await gas('health');renderSchedule();const l=state.health.links||{};setLink($('#generationLogLink'),l.generationLog);setLink($('#driveFolderLink'),l.regularMaterial);}catch(e){status($('#globalStatus'),shortErr(e),'error');}}
function setLink(a,url){if(url){a.href=url;a.classList.remove('disabled');}else{a.removeAttribute('href');a.classList.add('disabled');}}
function renderSchedule(){const list=state.health?.schedule||[];$('#scheduleGrid').innerHTML=list.map((x,i)=>`<div class="schedule-item"><span>${esc(x.time)}</span><b>${esc(x.label)}</b><small>${i===0?'starts':'staggered +30m'} · Mon–Fri</small></div>`).join('');}

function localToday(){const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'});return f.format(new Date());}
$('#todayBtn').onclick=()=>{$('#materialDate').value=localToday();loadMaterials();};
$('#loadBtn').onclick=loadMaterials;
async function loadMaterials(){const date=$('#materialDate').value;if(!date)return status($('#globalStatus'),'Choose a material date.','warn');const done=btnBusy($('#loadBtn'),'Loading…');clearStatus($('#globalStatus'));try{const d=await gas('materials',{date});state.date=date;state.materials=d.materials||[];state.assetCache.clear();renderMaterials();updateSummary();status($('#globalStatus'),`Loaded ${d.count}/5 materials for ${fmtDate(date)}. Production state is persistent in Google Sheets.`,'ok');}catch(e){status($('#globalStatus'),shortErr(e),'error');}finally{done();}}
function prod(entry){return entry.production||{p1:{status:'NOT_STARTED',version:0},p2:{status:'NOT_STARTED',version:0},pdf:{status:'NOT_STARTED',version:0},qcStatus:'PENDING'};}
function badgeClass(s){s=String(s||'');if(['DONE','READY','APPROVED'].includes(s))return'ok';if(s.includes('RUNNING')||s==='BUILDING')return'work';if(s==='ERROR')return'bad';return'';}
function assetCard(entry,page){const p=prod(entry)[page===1?'p1':'p2'];const missing=!p.fileId;const expired=p.expired;const canView=p.fileId&&!expired;const label=p.status==='ERROR'?'Retry':p.version?'Regenerate':'Generate manually';return`<div class="asset-card"><div class="asset-head"><b>Page ${page}</b><span class="pill ${badgeClass(p.status)}">${esc(p.status)}</span></div><div class="asset-meta"><span>v${p.version||0}</span><span>${p.generatedAt?fmtTime(p.generatedAt):'Not generated'}</span><span class="${expired?'expired':''}">${p.expiresAt?expiryText(p.expiresAt):'18h retention after generation'}</span></div><div class="asset-actions"><button class="btn btn-ghost" data-action="preview" data-page="${page}" ${canView?'':'disabled'}>View source</button>${p.driveUrl?`<a class="btn btn-ghost" href="${esc(p.driveUrl)}" target="_blank">Drive</a>`:''}<button class="btn btn-red" data-action="regen" data-page="${page}" ${entry.ready?'':'disabled'}>${label} P${page}</button></div></div>`;}
function card(entry){if(!entry.material)return`<article class="material panel missing"><b>${esc(entry.label)}</b><p>${esc(entry.error||'No material')}</p></article>`;const m=entry.material,p=prod(entry),pdf=p.pdf||{};return`<article class="material panel" data-id="${esc(m.materialId)}" data-key="${esc(entry.key)}"><div class="material-top"><div><span class="level">${esc(m.level)}</span><h3>${esc(m.topic)}</h3><p>${esc(m.theme)}</p></div><div class="schedule-time">${esc(entry.scheduleTime)} WIB</div></div><div class="chips"><span>Week ${esc(m.week)}</span><span>Meeting ${esc(m.meeting)}</span><span>${esc(m.materialId)}</span></div>${p.continuityWarning?`<div class="warning">⚠ ${esc(p.continuityWarning)}</div>`:''}${p.lastError?`<div class="error-box">${esc(p.lastError)}</div>`:''}<div class="asset-grid">${assetCard(entry,1)}${assetCard(entry,2)}</div><div class="pdf-row"><div><b>Final PDF</b><span class="pill ${badgeClass(pdf.status)}">${esc(pdf.status||'NOT_STARTED')}</span><small>${pdf.version?`v${pdf.version} · P1v${pdf.sourceP1Version} + P2v${pdf.sourceP2Version}`:'Built automatically after both pages'}</small></div><div class="pdf-actions">${pdf.driveUrl?`<a href="${esc(pdf.driveUrl)}" target="_blank" class="btn btn-navy">Open PDF</a>`:''}<button class="btn btn-ghost" data-action="pdf" ${(prod(entry).p1?.expired||prod(entry).p2?.expired||!prod(entry).p1?.fileId||!prod(entry).p2?.fileId)?'disabled':''}>Rebuild PDF</button><button class="btn ${p.qcStatus==='APPROVED'?'btn-ok':'btn-ghost'}" data-action="qc" ${pdf.status==='READY'?'':'disabled'}>${p.qcStatus==='APPROVED'?'✓ QC Approved':'Approve QC'}</button></div></div><div class="card-foot"><button class="btn btn-ghost" data-action="run">Run this level now</button><span>Run Now never repeats a page already attempted automatically or already generated.</span></div></article>`;}
function renderMaterials(){const g=$('#materialsGrid');g.innerHTML=state.materials.length?state.materials.map(card).join(''):`<div class="empty panel"><b>Load a date</b></div>`;bindCards();}
function findEntry(id){return state.materials.find(x=>x.material?.materialId===id);}
function bindCards(){$$('.material[data-id]').forEach(c=>c.onclick=async e=>{const t=e.target.closest('[data-action]');if(!t)return;const entry=findEntry(c.dataset.id);if(!entry)return;const a=t.dataset.action,page=Number(t.dataset.page||0);if(a==='preview')await preview(entry,page);if(a==='regen')await regen(entry,page);if(a==='pdf')await rebuildPdf(entry);if(a==='qc')await qc(entry);if(a==='run')await runNow(entry);});}
async function refreshEntry(entry){const d=await gas('materials',{date:state.date});state.materials=d.materials||[];renderMaterials();updateSummary();return state.materials.find(x=>x.material?.materialId===entry.material.materialId);}
async function preview(entry,page){const a=prod(entry)[page===1?'p1':'p2'];if(!a.fileId||a.expired)return;let raw=state.assetCache.get(a.fileId);if(!raw){try{const d=await gas('asset',{fileId:a.fileId});raw=`data:${d.mimeType||'image/png'};base64,${d.b64}`;raw=await watermark(raw);state.assetCache.set(a.fileId,raw);}catch(e){return status($('#globalStatus'),shortErr(e),'error');}}$('#modalLevel').textContent=entry.material.level;$('#modalTitle').textContent=`${entry.material.topic} · Page ${page} · v${a.version}`;$('#modalImage').src=raw;$('#imageModal').classList.remove('hidden');}
function loadImg(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src;});}
async function watermark(raw){const[source,mark]=await Promise.all([loadImg(raw),loadImg(new URL('./assets/kip-watermark.png',location.href).href)]);const c=document.createElement('canvas');c.width=source.naturalWidth;c.height=source.naturalHeight;const x=c.getContext('2d');x.drawImage(source,0,0);const w=Math.max(150,Math.round(c.width*.135)),h=Math.round(mark.naturalHeight*w/mark.naturalWidth),pad=Math.round(c.width*.022);x.save();x.globalAlpha=.16;x.drawImage(mark,c.width-w-pad,c.height-h-pad,w,h);x.restore();return c.toDataURL('image/png');}
async function regen(entry,page){const p=prod(entry)[page===1?'p1':'p2'];const verb=p.status==='ERROR'?'Retry':'Regenerate';if(!confirm(`${verb} Page ${page}?\n\nThis makes exactly ONE new paid OpenAI image request. The other page will NOT be regenerated. Existing PNG versions remain until their own 18-hour expiry.`))return;status($('#globalStatus'),`${verb} Page ${page} for ${entry.label}…`,'info');try{await gas('regenerate',{materialId:entry.material.materialId,page});await refreshEntry(entry);status($('#globalStatus'),`Page ${page} finished. If both pages exist, the PDF was rebuilt for free.`,'ok');}catch(e){await refreshEntry(entry).catch(()=>{});status($('#globalStatus'),shortErr(e),'error');}}
async function rebuildPdf(entry){if(!confirm('Rebuild this PDF from the current Page 1 + Page 2?\n\nThis does NOT call OpenAI and does not consume image-generation credits.'))return;try{await gas('rebuildPdf',{materialId:entry.material.materialId});await refreshEntry(entry);status($('#globalStatus'),'PDF rebuilt and saved to Google Drive.','ok');}catch(e){status($('#globalStatus'),shortErr(e),'error');}}
async function qc(entry){const approved=prod(entry).qcStatus==='APPROVED';try{await gas('qc',{materialId:entry.material.materialId,status:approved?'PENDING':'APPROVED'});await refreshEntry(entry);status($('#globalStatus'),approved?'QC returned to pending.':'Final PDF approved.','ok');}catch(e){status($('#globalStatus'),shortErr(e),'error');}}
async function runNow(entry){if(!confirm(`Run the normal production pipeline for ${entry.label} now?\n\nOnly missing, never-before-auto-attempted pages can make paid image calls. Existing successful/attempted pages are skipped. There are NO automatic retries.`))return;status($('#globalStatus'),`Running ${entry.label} production…`,'info');try{const d=await gas('runLevelNow',{date:state.date,levelKey:entry.key});await refreshEntry(entry);status($('#globalStatus'),d.message||'Level run finished.','ok');}catch(e){await refreshEntry(entry).catch(()=>{});status($('#globalStatus'),shortErr(e),'error');}}
function updateSummary(){const valid=state.materials.filter(x=>x.material);const n=k=>valid.filter(x=>prod(x)[k]?.status===(k==='pdf'?'READY':'DONE')).length;$('#summaryLoaded').textContent=`${valid.length} / 5`;$('#summaryP1').textContent=`${n('p1')} / 5`;$('#summaryP2').textContent=`${n('p2')} / 5`;$('#summaryPdf').textContent=`${n('pdf')} / 5`;$('#summaryQc').textContent=`${valid.filter(x=>prod(x).qcStatus==='APPROVED').length} / 5`;}
$('#closeModalBtn').onclick=()=>{$('#imageModal').classList.add('hidden');$('#modalImage').src='';};$('#imageModal').onclick=e=>{if(e.target.id==='imageModal')$('#closeModalBtn').click();};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#closeModalBtn').click();});
setInterval(()=>{if(state.materials.length){renderMaterials();updateSummary();}},60000);
$('#materialDate').value=localToday();checkSession();